### ISSUE TITLE
Add links to Dockerfiles

### ISSUE THREAD

**Issue by uniqueg** [avantikalal/covid-gene-expression#47]
The [docs for the infection project](project/SARS-CoV-2-infection/README.md) list used tools and links to corresponding Docker images. Where available, it might be helpful to add links to the corresponding `Dockerfile` for each Docker image so that people can build on the existing images.

**Comment by edawson** [comment]
This was resolved for most docker images by https://github.com/avantikalal/covid-gene-expression/pull/68 . A handful did not have dockerfiles on quay.
