### ISSUE TITLE
GO terms/pathways for selected human RBPs

### ISSUE THREAD

**Issue by avantikalal** [avantikalal/covid-gene-expression#56]
We are building a list of human RBPs that may interact with the SARS-CoV-2 genome. 

Once we have a list, match these proteins to their GO terms/pathways and check for GO/pathway enrichment.

**Comment by ambarishK** [comment]
After getting all human proteins as ortholog to SARS-CoV-2 virus assign ontology terms - cellular location, sub-cellular locations and metabolic pathways.
